# Generated by Django 3.1.7 on 2021-06-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_coursecontent_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='homeWork',
            new_name='homework',
        ),
    ]
