# Generated by Django 3.1.7 on 2021-06-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0003_auto_20210616_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='eduapp.course'),
        ),
    ]
