# Generated by Django 3.1.7 on 2021-06-16 13:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_auto_20210616_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent_course', to='eduapp.course', verbose_name='Select space'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='document',
            field=models.FileField(blank=True, null='True', upload_to='', verbose_name='Attach file'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='homework',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='true', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course-video/', verbose_name='Video'),
        ),
    ]
