# Generated by Django 3.1.7 on 2021-06-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduapp', '0005_auto_20210616_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank='true', upload_to='useravatars/', verbose_name='User avatar'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='related_course', to='eduapp.Course', verbose_name='Users spaces'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='type',
            field=models.CharField(choices=[('student', 'User')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aps', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
